Repository Financial-Times/o-test-component, pull requests merged in 2021-03, with the labels that each got.

#112 Make a test component with no Sass
  .stylelintignore
  .stylelintrc.cjs
  _index.scss
  demos/src/demo.scss
  main.scss
  origami.json
  package-lock.json
  package.json
  readme.md
  src/scss/_brand.scss
  src/scss/_functions.scss
  src/scss/_variables.scss
  test/scss/functions.test.scss
  test/scss/index.test.scss
Labels: component, release:patch

#114 use pull_request_target and not pull_request for the safe workflows
  .github/workflows/add-new-issues-and-pull-requests-to-origami-project-board.yml
  .github/workflows/apply-labels.yml
  .github/workflows/auto-approve.yml
  .github/workflows/sync-repo-labels.yml
Labels: component

#115 Set origamiVersion to "2.0"
  origami.json
Labels: component, release:beta, release:minor

#125 Update the table in the readme
  readme.md
Labels: component
