Repository Financial-Times/o-test-component, pull requests merged in 2021-06, with the labels that each got.

#182 Update readme with latest releases (not on the default branch)
  readme.md
Labels: component

#183 Add library component with no sass
  .github/workflows/test-origami-component.yml
  demos/src/demo.js
  demos/src/demo.scss
  demos/src/test-demo.mustache
  main.scss
  origami.json
  package.json
  readme.md
  src/scss/_brand.scss
  src/scss/_functions.scss
  test/scss/functions.test.scss
  test/scss/index.test.scss
Labels: component, release:patch

#184 bring back automatic publishing
  .github/workflows/automatic-tag-and-release.yml
Labels: release:patch

#186 Add v3 as a working component.
  demos/src/demo.js
  demos/src/demo.scss
  demos/src/test-demo.mustache
  main.scss
  origami.json
  package.json
  readme.md
  src/scss/_brand.scss
  src/scss/_functions.scss
  test/scss/functions.test.scss
  test/scss/index.test.scss
Labels: library, release:major
